spring:

  h2.console:
    enabled: true
    path: '/console'

  datasource:
    url: 'jdbc:h2:file:C:/Dawid/!! Programowanie/todo-app/todo-db'

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create

      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl




  flyway:
    baselineOnMigrate: true
    validateOnMigrate: false